import os
import ollama
import pandas as pd


def safe_str(value):
    """Return string if not NaN/empty, else None."""
    if pd.isna(value) or str(value).strip() == '':
        return None
    return str(value).strip()


def build_patient_context(subject_id, group):
    """Build a raw text summary of a patient's admission rows to feed into Ollama."""
    lines = [f"Patient ID: {subject_id}"]

    for _, row in group.iterrows():
        hadm_id        = safe_str(row.get('hadm_id'))
        admittime      = safe_str(row.get('admittime'))
        dischtime      = safe_str(row.get('dischtime'))
        deathtime      = safe_str(row.get('deathtime'))
        admission_type = safe_str(row.get('admission_type'))
        provider       = safe_str(row.get('admit_provider_id'))
        admission_loc  = safe_str(row.get('admission_location'))
        discharge_loc  = safe_str(row.get('discharge_location'))
        insurance      = safe_str(row.get('insurance'))
        language       = safe_str(row.get('language'))
        marital        = safe_str(row.get('marital_status'))
        race           = safe_str(row.get('race'))
        edregtime      = safe_str(row.get('edregtime'))
        edouttime      = safe_str(row.get('edouttime'))
        expire_flag    = safe_str(row.get('hospital_expire_flag'))

        lines.append(f"\nAdmission ID: {hadm_id}")
        if admittime:   lines.append(f"Admitted: {admittime}")
        if dischtime:   lines.append(f"Discharged: {dischtime}")
        if deathtime:   lines.append(f"Death time: {deathtime}")
        if admission_type: lines.append(f"Admission type: {admission_type}")
        if provider:    lines.append(f"Admitting provider: {provider}")
        if admission_loc: lines.append(f"Arrived from: {admission_loc}")
        if discharge_loc: lines.append(f"Discharged to: {discharge_loc}")
        if insurance:   lines.append(f"Insurance: {insurance}")
        if language and language != '?': lines.append(f"Language: {language}")
        if marital:     lines.append(f"Marital status: {marital}")
        if race:        lines.append(f"Race: {race}")
        if edregtime:   lines.append(f"ED registration: {edregtime}")
        if edouttime:   lines.append(f"ED departure: {edouttime}")
        if expire_flag: lines.append(f"Died during stay: {'Yes' if expire_flag == '1' else 'No'}")

    return "\n".join(lines)


def generate_nl_summary(context):
    """Use Ollama llama3 to generate a natural language summary of the patient's admission."""
    prompt = (
        "You are a clinical documentation assistant. "
        "Show the SQL code."
        "Given the following structured hospital admission data for a patient, "
        "write a clear, concise, natural language paragraph summarizing their admission — "
        "including when they were admitted, where they came from, where they were discharged to, "
        "any relevant demographic details, and whether they survived the stay. "
        "If there are multiple admissions, summarize each one. "
        "Do not add information that is not present. "
        "If details are missing, omit them naturally without calling attention to it.\n\n"
        f"{context}"
    )

    response = ollama.chat(
        model='llama3',
        messages=[{'role': 'user', 'content': prompt}]
    )
    return response['message']['content'].strip()

def generate_sql(subject_id):
    """Generate a SQL query to fetch all admissions for a given subject_id."""
    return (
        f"SELECT * FROM admissions\n"
        f"WHERE subject_id = {subject_id}\n"
        f"ORDER BY admittime ASC;"
    )


# --- MAIN SCRIPT ---

file_path = r"C:\Users\prana\OneDrive - Georgia Institute of Technology\ResearchMIBLAB\ehr_summarization_BioMibLab\mimic-iv-demo\mimic-iv-clinical-database-demo-2.2\hosp\admissions\admissions.csv"
# file_path = "admissions.csv"

df = pd.read_csv(file_path)
print(f"Loaded admissions: {df.shape}")
print(f"Columns found: {list(df.columns)}")

# --- NL PROSE OUTPUT (grouped by patient, generated by Ollama) ---
output_file = r"C:\Users\prana\OneDrive - Georgia Institute of Technology\ResearchMIBLAB\ehr_summarization_BioMibLab\pipelineScalingCode\output\admissions_prose.txt"

os.makedirs(os.path.dirname(output_file), exist_ok=True)

grouped = df.groupby('subject_id')
print(f"Generating NL summaries for {len(grouped)} patients via Ollama llama3...")

with open(output_file, "w", encoding="utf-8") as f:
    for i, (subject_id, group) in enumerate(grouped):
        context = build_patient_context(subject_id, group)
        summary = generate_nl_summary(context)
        f.write(f"=== Patient {subject_id} ===\n")
        f.write(summary + "\n\n")
        print(f"  [{i+1}/{len(grouped)}] Patient {subject_id} done.")

print(f"Saved NL summaries to {output_file}")

# --- SQL OUTPUT (one query per patient) ---
sql_output_file = r"C:\Users\prana\OneDrive - Georgia Institute of Technology\ResearchMIBLAB\ehr_summarization_BioMibLab\pipelineScalingCode\output\admissions_queries.sql"

with open(sql_output_file, "w", encoding="utf-8") as f:
    for subject_id in df['subject_id'].unique():
        f.write(generate_sql(subject_id) + "\n\n")

print(f"Saved {df['subject_id'].nunique()} SQL queries to {sql_output_file}")